sudo: false

language: go

go:
  - 1.10.x

before_install:
  - go get github.com/mattn/goveralls

before_script:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

script:
  - goveralls -service=travis-ci
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)