sudo: false

language: go

go:
  - 1.9.x
  - 1.x

before_script:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

script:
  - go test -v -race ./...  # Run all the tests with the race detector enabled

after_success:
  - bash <(curl -s https://codecov.io/bash)